### ISSUE TITLE
Question about background.

### ISSUE THREAD

**Issue by chaoseternally** [Kofituo/pound#2]
@Kofituo , Hello i was trying to figure out how to set a background at exact position (like from (x1,y1) to (x10,y10) ) on screen, but i couldn't figure it out, so i thought about asking it here.

**Comment by Kofituo** [comment]
Could you explain further? What background are you referring to?

**Comment by chaoseternally** [comment]
[SetBackgroundColor](https://docs.rs/crossterm/0.13.3/crossterm/style/struct.SetBackgroundColor.html) struct in crossterm.
I want to display something like this 
1. To create some autocomplete functionality.
![preview](https://user-images.githubusercontent.com/35003073/51228901-ee8f5f00-198c-11e9-9ea5-64b45b26406a.PNG)

2. Or some mini window like this 
    To create many stuff like file explorer, find file, etc.
![preview_two](https://madskjeldgaard.dk/img/full/scideneovim.png)

**Comment by Kofituo** [comment]
Okay I understand. 

The colors are set within the `String` printed to the terminal. So you'd have to color them appropriately.

1.  You could create a string wrapper, similar to what I've in my tutorial. 
2. Create a `push` / `push_str` functions and then check if the new string being added falls with the specified range. You could simply do so by checking the len of the `str` being added. 
3. If it falls within your specified range, first add `SetBackgroundColor(color)` to your string. Next add the range of the string you want to color. Reset set the background color. And then add the remaining range. 
4. Alternatively, since you want to color a fixed range, a more convenient option maybe to modify your output string just before you write it to the terminal. In this method, you do not need to create a new type: Add `SetBackgroundColor(color)` before your start index, then reset background color after your end index. Since this method inserts randomly into a string, it might be slightly slower than the former method. However that should be a concern if only you experience lag. I don't think you'll though. Rust is really fast.

**Comment by Kofituo** [comment]
However, depending on your program, the implementation might be slightly different. If you understand the principle I just gave, you'd be able to do it!

**Comment by chaoseternally** [comment]
Oh so i should create a new struct that will override "EditorContents" struct?

**Comment by Kofituo** [comment]
Not necessarily a new one. You could simply modify it to suit your needs.
